supp_dic_iso_to_genus = {
    "mon" : "Mongolic",
    "cos" : "Romance",
    'lat': 'Romance',
    'heb': 'Semitic',
    'epo': 'Unknown',
    'kri': 'Creoles and Pidgins',
    'hye': 'Armenian',
    'san': 'Indic',
    'ell': 'Greek',
    'zho': 'Chinese',
    'est' : 'Finnic',
    'srp' : 'Slavic',
    'hrv' : 'Slavic',
    'hif' : 'Indic',
    'orm' : 'Lowland East Cushitic',
    'aze' : 'Turkic',
    'zho' : 'Chinese',
    'mon' : 'Mongolic',
    'ori' : 'Indic',
    'nob' : 'Germanic',
    'nno' : 'Germanic',
    'twi' : 'Unknown',
    'cos' : 'Romance',
    'scn' : 'Romance',
    'sco' : 'Celtic',
    'lat' : 'Romance',
    'msa' : 'Malayo-Sumbawan',
    'stq' : 'Germanic',
    'kiu' : 'Iranian',
    'lvs' : 'Baltic',
    'heb' : 'Semitic',
    'bjn' : 'Unknown',
    'als' : 'Albanian',
    'que' : 'Yuman',
    'uzb' : 'Turkic',
    'lim' : 'Germanic',
    'swa' : 'Bantu',
    'epo' : 'Unknown',
    'kri' : 'Unknown',
    'wes' : 'Creoles and Pidgins',
    'zxx' : 'Unknown',
    'nep' : 'Indic',
    'bik' : 'Greater Central Philippine',
    'azj' : 'Turkic',
    'szl' : 'Unknown',
    'pne' : 'Unknown',
    'san' : 'Unknown',
    'mlg' : 'Barito',
    'sms' : 'Unknown',
    'ell' : 'Greek',
    'mhl' : 'Unknown',
    'grn' : 'Maweti-Guarani',
    'ara' : 'Semitic',
    "pbt" : "Iranian",
    "ina" : "Unknown",
    "hne" : "Indic",
    "smj" : "Unknown",
    "nki" : "Unknown",
    "new" : "Himalayish",
    "yid" : "Germanic",
    "lmo" : "Unknown",
    "pez" : "Unknown",
    "myk" : "Unknown",
    "fat" : "Unknown",
    "npl" : "Aztecan",
    "phm" : "Unknown",
    "tsc" : "Bantu",
    "srd" : "Romance",
    "pus" : "Iranian",
    "bzj" : "Creoles and Pidgins",
    "fas" : "Iranian",
    "sdh" : "Iranian",
    "kal" : "Eskimo",
    "smn" : "Unknown",
    "hmn" : "Hmongic",
    "cfm" : "Kuki-Chin",
    "dln" : "Kuki-Chin",
    "Unknown" : "Unknown",
    "bua" : "Mongolic",
    "rhg" : "Unknown",
    "bar" : "Germanic",
    "qxn" : "Quechuan",
    "pdc" : "Germanic",
    "gom" : "Indic",
    "qve" : "Quechuan",
    "swc" : "Bantu",
    "nbl" : "Bantu",
    "nng" : "Unknown",
    "pmx" : "Unknown",
    "zom" : "Unknown",
    "wlx" : "Unknown",
    "mwl" : "Romance",
    "cpc" : "Unknown",
    "nyu" : "Unknown",
    "aln" : "Albanian",
    "qwh" : "Quechuan",
    "tpa" : "Unknown",
    "wmw" : "Unknown",
    "biv" : "Unknown",
    "lsi" : "Unknown",
    "xog" : "Unknown",
    "ido" : "Unknown",
    "dgi" : "Unknown",
    "rar" : "Unknown",
    "aym" : "Aymaran",
    "tul" : "Unknown",
    "bwq" : "Western Mande",
    "sbd" : "East Strickland",
    "bmv" : "Unknown",
    "wbm" : "Unknown",
    "ztq" : "Zapotecan",
    "twx" : "Unknown",
    "acq" : "Semitic",
    "pfl" : "Germanic",
    "loq" : "Bantu",
    "akp" : "Unknown",
    "rmy" : "Indic",
    "kqe" : "Unknown",
    "cpb" : "Unknown",
    "ncx" : "Aztecan",
    "sck" : "Unknown",
    "mfq" : "Unknown",
    "uzs" : "Turkic",
    "fuq" : "Peul-Serer",
    "olo" : "Unknown",
    "vro" : "Unknown",
    "bps" : "Unknown",
    "myx" : "Unknown",
    "pua" : "Unknown",
    "cjk" : "Unknown",
    "bkv" : "Unknown",
    "ndc" : "Bantu",
    "fil" : "Greater Central Philippine",
    "kmy" : "Unknown",
    "rue" : "Slavic",
    "ile" : "Unknown",
    "hbo" : "Semitic",
    "bpy" : "Indic",
    "bal" : "Iranian",
    "syl" : "Indic",
    "ktb" : "Unknown",
    "ext" : "Romance",
    "esk" : "Eskimo",
    "yml" : "Unknown",
    "ckm" : "Slavic",
    "aby" : "Unknown",
    "mkn" : "Unknown",
    "mup" : "Indic",
    "yon" : "Unknown",
    "acf" : "Creoles and Pidgins",
    "sbl" : "Unknown",
    "lgl" : "Unknown",
    "fmu" : "Dravidian",
    "fit" : "Finnic",
    "lzh" : "Chinese",
    "sgs" : "Baltic",
    "xsb" : "Unknown",
    "tog" : "Bantu",
    "dik" : "Unknown",
    "buk" : "Unknown",
    "nhe" : "Aztecan",
    "qvh" : "Quechuan",
    "bzi" : "Burmese-Lolo",
    "qup" : "Quechuan",
    "pnb" : "Indic",
    "dop" : "Unknown",
    "lem" : "Unknown",
    "qxo" : "Quechuan",
    "xnn" : "Northern Luzon",
    "rmn" : "Romani",
    "rup" : "Romance",
    "swp" : "Unknown",
    "lsm" : "Bantu",
    "loe" : "Unknown",
    "chw" : "Bantu",
    "ksc" : "Unknown",
    "ttj" : "Bantu",
    "khy" : "Bantu",
    "fur" : "Romance",
    "kln" : "Unknown",
    "kqa" : "Unknown",
    "llb" : "Unknown",
    "ikk" : "Arhuacic",
    "ghe" : "Unknown",
    "nwx" : "Himalayish",
    "sim" : "Unknown",
    "grc" : "Greek",
    "arq" : "Semitic",
    "ttq" : "Berber",
    "yal" : "Unknown",
    "swk" : "Bantu",
    "nch" : "Aztecan",
    "rcf" : "Creoles and Pidgins",
    "rjs" : "Indic",
    "nuj" : "Bantu",
    "apc" : "Semitic",
    "ars" : "Semitic",
    "ajp" : "Unknown",
    "mlh" : "Unknown",
    "sfw" : "Unknown",
    "mzw" : "Unknown",
    "wln" : "Romance",
    "enm" : "Germanic",
    "ltg" : "Baltic",
    "vec" : "Romance",
    "hag" : "Ndu",
    "kpf" : "Ndeiram",
    "lfn" : "Unknown",
    "mfz" : "Unknown",
    "acd" : "Unknown",
    "cce" : "Bantu",
    "mwn" : "Bantu",
    "ikw" : "Igboid",
    "mbh" : "Unknown",
    "bcc" : "Iranian",
    "kkj" : "Bantu",
    "gng" : "Oti-Volta",
    "plw" : "Greater Central Philippine",
    "bzh" : "Central Malayo-Polynesian",
    "sdq" : "Land Dayak",
    "tlh" : "Unknown",
    "tnr" : "Unknown",
    "kpe" : "Western Mande",
"quf" : "Quechuan",
    "vid" : "Bantu",
    "rop" : "Creoles and Pidgins",
    "nzi" : "Tano",
    'yat' : "Bantu",
    'dig' : "Bantu",
    'kon' : "Bantu",
    'nop' : "Finisterre",
    'kub' : "Jukunoid",
    'kqs' : "Unknown",
    'koo' : "Bantu",
    'ada' : "Ga-Dangme",
    'dhm' : "Bantu",
    'mwc' : "Oceanic",
    'shr' : "Bantu",
    'dks' : "Western Nilotic",
    'kno' : "Western Mande",
    'vmw' : "Bantu",
    'kwy' : "Bantu",
    'alz' : "Western Nilotic",
    'gwr' : "Bantu",
    'dug' : "Bantu",
    'eza' : "Igboid",
    'kom' : "Permic",
    'rub' : "Bantu",
    'tum' : "Bantu",
    'hav' : "Bantu",
    'icr' : "Creoles and Pidgins",
    'mti' : "South Sulawesi",
    'agw' : "Oceanic",
    'vap' : "Unknown",
    'akb' : "Northwest Sumatra-Barrier Islands",
    'kwf' : "Oceanic",
    'ngl' : "Bantu",
    'kvj' : "Biu–Mandara",
    'kqn' : "Bantu",
    'cgc' : "Greater Central Philippine",
    'skg' : "Barito",
    'cwe' : "Bantu",
    'met' : "Oceanic",
    'nss' : "Oceanic",
    'ngp' : "Bantu",
    'thk' : "Bantu",
    'arg' : "Romance",
    'kwj' : "Bantu",
    'asg' : "Benue-Congo Plateau",
    'kmm' : "Kuki-Chin",
    'nyy' : "Bantu",
    'caf' : "Athapaskan",
    'nhd' : "Unknown",
    'wuv' : "Oceanic",
    'pah' : "Unknown",
    'fue' : "Unknown",
    'bnj' : "Greater Central Philippine",
    'kus' : "Oti-Volta",

}